apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: additional-scrape-configs
stringData:
  prometheus-additional.yaml: |-
    - job_name: "node-exporter"
      static_configs:
        - targets: ["node-exporter-prometheus-node-exporter.monitoring:9100"]


 #add blackbox here later