apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    prometheus: main
    alertmanager: alertmanager-main
spec:
  replicas: 1
  logLevel: debug

