apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels: 
    alertmanagerConfig: alertmanager
spec:
  route:
    receiver: 'email-alert'
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
  receivers:
    - name: 'email-alert'
      emailConfigs:
        - to: 'eklegend02@gamil.com'
          from: 'eklegend02@gmail.com'
          smarthost: 'smtp.gmail.com:587'
          authUsername: 'eklegend02@gmail.com'
          authPassword:
            name: alertmanager-smtp-secret
            key: smtp_auth_password
          requireTLS: false
