# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: monitoring
#   name: grafana
#   labels:
#     app.kubernetes.io/instance: grafana
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: grafana
#     app.kubernetes.io/version: 10.4.1
#     prometheus: main
# stringData:
#   grafana.ini : |
#     [analytics]
#     check_for_updates = true
    
#     [grafana_net]
#     url = https://grafana.net
    
#     [log]
#     mode = console
    
#     [paths]
#     data = /var/lib/grafana/
#     logs = /var/log/grafana
#     plugins = /var/lib/grafana/plugins
#     provisioning = /etc/grafana/provisioning
    
#     [server]
#     domain = ''

#     [alerting]
#     enabled = true
#     check_interval = 1m
    

#     [slack]
#     enabled = true
#     webhook_url = https://hooks.slack.com/services/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
#     channel = "alerts"
#     username = Grafana