apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-main
  namespace: monitoring
  labels:
    prometheus: main
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: main
  podMonitorSelector:
    matchLabels:
      prometheus: main
  podMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus # we called this because a namespaceselector is called and we use the namespace.yaml format
  logFormat: logfmt
  logLevel: info
  retention: 7d
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager
      port: web
      
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       resources:
  #         requests:
  #           storage: 1Gi
