# trunk-ignore-all(prettier)
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-main
  namespace: monitoring
  labels:
    prometheus: main
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: main
  podMonitorSelector:
    matchLabels:
      prometheus: main
  podMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  ruleNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  ruleSelector:
    matchLabels:
        prometheus: main
  logFormat: logfmt
  logLevel: info
  retention: 7d
  alerting:
    alertmanagers:
      - name: alertmanager-main
        namespace: monitoring
        port: web
  volumes:
    - name: grafana
      configMap:
        name: grafana
  volumeMounts:
    - name: grafana
      mountPath: /etc/grafana/grafana.ini
      subPath: grafana.ini