apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-app
  namespace: monitoring
  labels:   
    prometheus: main # we link this with the prometheus.yaml labels
spec: 
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: prometheus-app
  podMetricsEndpoints:
  - port: http
    path: /metrics