apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: prometheus-app
